### ISSUE TITLE
Client keeps disconnecting

### ISSUE THREAD

**Issue by unichargepay** [sbtinstruments/aiomqtt#253]
Hello.

I'm trying to use the library, but I'm running constantly into issues.
I used the examples, almost every one, that is posted onb the docu website, however, I can't get it to run correctly.

I have local mqtt broker with credentials running on a raspberry pi 4.

What I want is to publish a message every n seconds.
This is a test for a future code, that will check a device state using API and publish the states using client.
This action will be done in cycles after n seconds, that is why.

Here is the code, that i put together using the examples.

The reading from the database bit works correctly,

```
import asyncio
import logging
import aiomqtt
import mysql.connector
import json

# Initialize the logger
logger = logging.getLogger(__name__)
FORMAT = "[%(filename)s:%(lineno)s - %(funcName)20s() ] %(message)s"
logging.basicConfig(format=FORMAT)
logger.setLevel(logging.DEBUG)

# Global variables for configuration
database = ""
user = ""
password = ""
mqtt_config = {}  # {"JSON_TEMPLATE_MQTT":{"broker":"service_mqtt","port":"1883","username":"","password":"","topics":{"outputs":"outputs/output"}}}
reconnect_interval = 5  # In seconds


async def load_configuration():
    global database
    global user
    global password
    global mqtt_config

    connection = None
    cursor = None

    try:
        connection = mysql.connector.connect(host='localhost',
                                             port='3306',
                                             database=database,
                                             user=user,
                                             password=password)

        cursor = connection.cursor()

        if connection.is_connected():
            logger.debug("Connected to the database.")
            sql_select_query = 'SELECT mqtt FROM configuration WHERE id = 1'
            cursor.execute(sql_select_query)
            records = cursor.fetchall()

            if records:
                mqtt_config = json.loads(records[0][0])
                logger.debug("MQTT configuration loaded: %s", mqtt_config)
            else:
                logger.warning("No MQTT configuration found in the database.")

        else:
            logger.error("Couldn't connect to the database.")

    except mysql.connector.Error as e:
        logger.error("Error loading configuration from the database: %s", e)
    finally:
        if cursor:
            cursor.close()
        if connection and connection.is_connected():
            connection.close()  # Fix: Use connection.close() instead of connection close()


async def publish_temperature(client):
    while True:
        await client.publish("temperature/outside", payload=28.4)
        await asyncio.sleep(5)  # Sleep for 5 seconds


async def publish_humidity(client):
    while True:
        await client.publish("humidity/inside", payload=0.38)
        await asyncio.sleep(5)  # Sleep for 5 seconds


async def main():
    global mqtt_config

    await load_configuration()

    async with aiomqtt.Client(hostname="localhost",
                              port=int(mqtt_config["JSON_TEMPLATE_MQTT"]["port"]),
                              username=mqtt_config["JSON_TEMPLATE_MQTT"]["username"],
                              password=mqtt_config["JSON_TEMPLATE_MQTT"]["password"],
                              client_id="service_tesla") as client:

        print("Client connected.")

        # Start the tasks to publish temperature and humidity readings
        task_temperature = asyncio.create_task(publish_temperature(client))
        task_humidity = asyncio.create_task(publish_humidity(client))

        # Wait for both tasks to complete
        await task_temperature
        await task_humidity

if __name__ == '__main__':
    asyncio.run(main())
```

This is the error i get:

```
Client connected.
Traceback (most recent call last):
  File "/home/pi/source_tesla/app/service_tesla.py", line 93, in main
    await task_temperature
  File "/home/pi/source_tesla/app/service_tesla.py", line 65, in publish_temperature
    await client.publish("temperature/outside", payload=28.4)
  File "/home/pi/.local/lib/python3.9/site-packages/aiomqtt/client.py", line 117, in decorated
    return await method(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/aiomqtt/client.py", line 652, in publish
    raise MqttCodeError(info.rc, "Could not publish message")
aiomqtt.error.MqttCodeError: [code:4] The client is not currently connected.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/source_tesla/app/service_tesla.py", line 97, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/source_tesla/app/service_tesla.py", line 94, in main
    await task_humidity
  File "/home/pi/.local/lib/python3.9/site-packages/aiomqtt/client.py", line 1050, in __aexit__
    if self._early_out_on_disconnected():
  File "/home/pi/.local/lib/python3.9/site-packages/aiomqtt/client.py", line 525, in _early_out_on_disconnected
    raise disc_exc
aiomqtt.error.MqttCodeError: [code:7] The connection was lost.
[base_events.py:1738 - default_exception_handler() ] Task exception was never retrieved
future: <Task finished name='Task-4' coro=<publish_humidity() done, defined at /home/pi/source_tesla/app/service_tesla.py:69> exception=MqttCodeError('Could not publish message')>
Traceback (most recent call last):
  File "/home/pi/source_tesla/app/service_tesla.py", line 71, in publish_humidity
    await client.publish("humidity/inside", payload=0.38)
  File "/home/pi/.local/lib/python3.9/site-packages/aiomqtt/client.py", line 117, in decorated
    return await method(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/aiomqtt/client.py", line 652, in publish
    raise MqttCodeError(info.rc, "Could not publish message")
aiomqtt.error.MqttCodeError: [code:4] The client is not currently connected.
```

Can I get some insight, how to modify the code, or what could be possibly happening?
I'm using MQTTFX tool to debug the messages and connect to the broker, whichs works correctly, so the broker does work.

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


python3 --version
Python 3.9.2

/ # mosquitto -h
mosquitto version 2.0.18

mosquitto is an MQTT v5.0/v3.1.1/v3.1 broker.

Usage: mosquitto [-c config_file] [-d] [-h] [-p port]

 -c : specify the broker config file.
 -d : put the broker into the background after starting.
 -h : display this help.
 -p : start the broker listening on the specified port.
      Not recommended in conjunction with the -c option.
 -v : verbose mode - enable all logging types. This overrides
      any logging options given in the config file.

See https://mosquitto.org/ for more information.

/ #

```

Thank you, very much.

**Comment by empicano** [comment]
Thanks @SamAlhabash for helping out! 👍 My first guess would also be that client identifiers are used multiple times. To solve this, I'd try to run the [minimal example to publish a message](https://sbtinstruments.github.io/aiomqtt/publishing-a-message.html) and see if that works, and what the differences are to the code you posted here.

I'll close this as there hasn't been any more discussion. If there's anything left unsolved or unclear, please reopen this issue!
